<template>
  <div class="mt-4">
    <h1 class="">SURVEILLANCE</h1>
    <div class="text-left pt-2">
      <p>CCTV systems provide surveillance capabilities used in the protection of people, assets, and systems. A CCTV system serves mainly as a security force multiplier, providing surveillance for a larger area, more of the time, than would be feasible with security personnel alone.</p>
      <p>CCTV systems are often used to support comprehensive security systems by incorporating video coverage and security alarms for barriers, intrusion detection, and access control. For example, a CCTV system can provide the means to assess an alarm generated by an intrusion detection system and record the event.</p>
      <p>A CCTV system links a camera to a video monitor using a direct transmission system. This differs from broadcast television where the signal is transmitted over the air and viewed with a television. New approaches within the CCTV industry are moving towards more open architecture and transmission methods versus the closed circuit, hard-wired connection systems of the past.</p>
      <p>CCTV systems have many components with a variety of functions, features, and specifications. Key components include cameras, lenses, data distribution, power, and lighting, among others. CCTV technologies continuously undergo feature refinements to improve performance in areas such as digital equipment options, data storage, component miniaturization, wireless communications, and automated image analysis.</p>

      <h3 class="mt-2">COMPONENTS OF CCTV SYSTEMS</h3>
      <p>CCTV uses components that are directly connected to generate, transmit, display, and store video data. A CCTV system can be as simple as a camera purchased from a retail electronics store connected to a video monitor.</p>
      <p>However, larger systems operated by professional security personnel are comprised of a number of components falling into several basic categories:</p>
      <ul>
        <li>Cameras</li>
        <li>Lenses</li>
        <li>Housings and mounts</li>
        <li>Monitors</li>
        <li>Switchers and multiplexers and</li>
        <li>Video recorders</li>
      </ul>
    </div>
    <div class="container-fluid">
      <div class="row mt-5">
        <div class="survCamCont col-md-6 my-4 my-lg-3 px-lg-1">
          <img class="survCam img-responsive" src="../../../public/images/our_services/surve.jpg" alt="">
        </div>
        <div class="survCamCont col-md-6 my-4 my-lg-3 px-lg-1">
          <img class="survCam img-responsive" src="../../../public/images/surv/component.jpg" alt="">
        </div>
        <div class="survCamCont col-md-6 my-4 my-lg-3 px-lg-1">
          <img class="survCam img-responsive" src="../../../public/images/surv/bullet.jpg" alt="">
        </div>
        <div class="survCamCont col-md-6 my-4 my-lg-3 px-lg-1">
          <img class="survCam img-responsive" src="../../../public/images/surv/bullet2.jpg" alt="">
        </div>
        <div class="survCamCont col-md-6 my-4 my-lg-3 px-lg-1">
          <img class="survCam img-responsive" src="../../../public/images/surv/dome.jpg" alt="">
        </div>
        <div class="survCamCont col-md-6 my-4 my-lg-3 px-lg-1">
          <img class="survCam img-responsive" src="../../../public/images/surv/ptz.jpg" alt="">
        </div>
      </div>
    </div>
    <div class="my-3">
      <p><strong>At DILIGENT PLOUTOS</strong>, we pride ourselves with quality <strong>surveillance services</strong> such as <strong>installations</strong>, <strong>transmission over a wireless or wired network</strong>, <strong>maintenance</strong> and <strong>supplies of CCTV components</strong>.</p>
    </div>
  </div>

</template>

<script>
export default {
  name: 'surveillance'
}
</script>
